<?php

namespace Abds\MaincoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Album_PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Album_PhotoRepository extends EntityRepository
{
}