<?php

namespace Abds\MaincoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EnjoyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnjoyRepository extends EntityRepository
{
}