<?php

namespace Abds\MaincoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Game_UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Game_UserRepository extends EntityRepository
{
}