<?php

namespace Abds\MaincoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * personalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class personalRepository extends EntityRepository
{
}